name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Telegram Notify (Success)
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.chat }}
        token: ${{ secrets.token }}
        message: |
          ✅ Build ${{ github.run_number }} succeeded on ${{ github.ref }}
          Author: ${{ github.event.head_commit.author.name }} (${{ github.event.head_commit.author.email }})
          
          Commit message: ${{ github.event.head_commit.message }}
    - name: Telegram Notify (Fail)
      uses: appleboy/telegram-action@master
      if: ${{ failure() }}
      with:
        to: ${{ secrets.chat }}
        token: ${{ secrets.token }}
        message: |
          ❌ Build ${{ github.run_number }} failed on ${{ github.ref }}
          Author: ${{ github.event.head_commit.author.name }} (${{ github.event.head_commit.author.email }})
          
          Commit message: ${{ github.event.head_commit.message }}
